#!/bin/sh

# PROVIDE: bsdrngd
# REQUIRE: devd
# KEYWORD: nojail

. /etc/rc.subr

name="bsdrngd"
rcvar="bsdrngd_enable"
command="/usr/local/sbin/bsdrngd"

load_rc_config $name

bytes="${bsdrngd_bytes:-16}"
device="${bsdrngd_device:-/dev/cuaU0}"
interval="${bsdrngd_interval:-2}"
command_args="-d -b ${bytes} -s ${interval} ${device}"

run_rc_command "$1" 
